# Generated by Django 5.0.1 on 2024-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_product_dateadded_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='priceChange',
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='dateAdded',
            field=models.DateTimeField(),
        ),
    ]
