# Generated by Django 5.0.1 on 2024-01-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_remove_producthistory_pricechange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSearchText',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
