# Generated by Django 5.0.1 on 2024-01-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_product_productsearchtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productSearchText',
            new_name='searchText',
        ),
    ]
