# Generated by Django 5.0.1 on 2024-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_rename_productsearchtext_product_searchtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='priceChange',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
