# Generated by Django 5.0.1 on 2024-01-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_producthistory_pricechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthistory',
            name='url',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
